### ISSUE TITLE
Uncaught (in promise) Error: Unsupported model type: whisper

### ISSUE THREAD

**Issue by Keith-Hon** [xenova/whisper-web#24]
models.js:3384 Uncaught (in promise) Error: Unsupported model type: whisper
    at AutoModelForCTC.from_pretrained (models.js:3384:19)
    at async pipelines.js:2071:33
from_pretrained @ models.js:3384

I finetuned my whisper-small model with peft and converted into onnx with 

https://github.com/xenova/transformers.js/blob/main/scripts/convert.py

**Comment by deeeed** [comment]
I have similar issue using xenova/whisper-medium

**Comment by abuchnick-aiola** [comment]
Also running into this ... Can this be answered please ? 
Are we missing some voodoo in order to get it to work ?
